# Generated by Django 3.1.1 on 2020-09-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouterDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sapid', models.CharField(max_length=18)),
                ('Host_name', models.CharField(max_length=14)),
                ('Loop_back', models.CharField(max_length=20)),
                ('Mac_address', models.CharField(max_length=14)),
            ],
        ),
    ]
